spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    platform: h2
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: sa
      password:
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2 # default /he-console
